INSERT INTO "languages" VALUES(0,'aar','aa','aar','Afro-Asiatic','Afaraf','Afar','afar','afar','阿法尔语l; 阿法语','афар','Afar');
INSERT INTO "languages" VALUES(1,'abk','ab','abk','Northwest Caucasian','Аҧсуа','Abkhazian','abkhaze','abjaso','阿布哈兹语','абхазский','Abchasisch');
INSERT INTO "languages" VALUES(2,'afr','af','afr','Indo-European','Afrikaans','Afrikaans','Afrikaans','Afrikaans','阿非利堪斯语; 南非荷兰语; 南非语','африкаанс','Afrikaans');
INSERT INTO "languages" VALUES(3,'aka','ak','aka','Niger–Congo','Akan','Akan','akan','acano','阿坎语','акан','Akan');
INSERT INTO "languages" VALUES(4,'amh','am','amh','Afro-Asiatic','አማርኛ','Amharic','amharique','amárico','阿姆哈拉语','амхарский','Amharisch');
INSERT INTO "languages" VALUES(5,'ara','ar','ara','Arabic','العربية','Arabic','arabe','árabe','阿拉伯语','арабский','Arabisch');
INSERT INTO "languages" VALUES(6,'arg','an','arg','Indo-European','aragonés','Aragonese','aragonais','aragonés','阿拉贡语','арагонский','Aragonisch');
INSERT INTO "languages" VALUES(7,'asm','as','asm','Indo-European','অসমীয়া','Assamese','assamais','asamés','阿萨姆语','ассамский','Asamiya');
INSERT INTO "languages" VALUES(8,'ava','av','ava','Northeast Caucasian','авар','Avaric','avar','avaro','阿瓦尔语','аварский',NULL);
INSERT INTO "languages" VALUES(9,'ave','ae','ave','Indo-European','avesta','Avestan','avestique',NULL,'阿维斯陀语','авестийский',NULL);
INSERT INTO "languages" VALUES(10,'aym','ay','aym','Aymaran','aymar','Aymara','aymara','aimara','艾马拉语','аймара','Aymara');
INSERT INTO "languages" VALUES(11,'aze','az','aze','Turkic','Azərbaycan','Azerbaijani','azéri','azerbayano','阿塞拜疆语','азербайджанский','Aserbaidschanisch');
INSERT INTO "languages" VALUES(12,'bak','ba','bak','Turkic','башҡорт','Bashkir','bachkir','baskir','巴什基尔语','башкирский','Baschkirisch');
INSERT INTO "languages" VALUES(13,'bam','bm','bam','Niger–Congo','bamanankan','Bambara','bambara',NULL,'班巴拉语','бамана',NULL);
INSERT INTO "languages" VALUES(14,'bel','be','bel','Indo-European','беларуская','Belarusian','biélorusse','bielorruso','白俄罗斯语','белорусский','Weißrussisch');
INSERT INTO "languages" VALUES(15,'ben','bn','ben','Indo-European','বাংলা','Bengali','bengali','bengalí','孟加拉语','бенгальский','Bengalisch');
INSERT INTO "languages" VALUES(16,'bis','bi','bis','English Creole','Bislama','Bislama','bichlamar','bislama','比斯拉马语; 比斯拉玛语','бислама','Bislama');
INSERT INTO "languages" VALUES(17,'bod','bo','tib','Sino-Tibetan','བོད་ཡིག','Tibetan','tibétain','tibetano','藏语; 卫藏语','тибетский','Tibetisch');
INSERT INTO "languages" VALUES(18,'bos','bs','bos','Indo-European','bosanski','Bosnian','bosniaque','bosnio','波斯尼亚语; 波士尼亚语','боснийский','Bosnisch');
INSERT INTO "languages" VALUES(19,'bre','br','bre','Indo-European','brezhoneg','Breton','breton','bretón','布列塔尼语','бретонский','Bretonisch');
INSERT INTO "languages" VALUES(20,'bul','bg','bul','Indo-European','български','Bulgarian','bulgare','búlgaro','保加利亚语','болгарский','Bulgarisch');
INSERT INTO "languages" VALUES(21,'cat','ca','cat','Indo-European','català','Catalan','catalan','catalán','加泰隆尼亚语; 加泰罗尼亚语; 加泰隆语; 瓦伦西亚语','каталанский','Katalanisch');
INSERT INTO "languages" VALUES(22,'ces','cs','cze','Indo-European','čeština','Czech','tchèque','checo','捷克语','чешский','Tschechisch');
INSERT INTO "languages" VALUES(23,'cha','ch','cha','Austronesian','Chamoru','Chamorro','chamorro','chamorro','查莫罗语','чаморро','Chamorro');
INSERT INTO "languages" VALUES(24,'che','ce','che','Northeast Caucasian','нохчийн','Chechen','tchétchène','checheno','车臣语','чеченский','Tschetschenisch');
INSERT INTO "languages" VALUES(25,'chu','cu','chu','Indo-European','ѩзыкъ словѣньскъ','Old Church Slavonic','slavon d''église vieux','eslavo eclesial','古教会斯拉夫语','церковнославянский','Altkirchenslawisch');
INSERT INTO "languages" VALUES(26,'chv','cv','chv','Turkic','Чӑваш','Chuvash','tchouvache','chuvasio','楚瓦什语','чувашский','Tschuwaschisch');
INSERT INTO "languages" VALUES(27,'cor','kw','cor','Indo-European','Kernewek','Cornish','cornique','córnico','康沃尔语; 康瓦尔语','корнский','Kornisch');
INSERT INTO "languages" VALUES(28,'cos','co','cos','Indo-European','corsu','Corsican','corse','corso','科西嘉语','корсиканский','Korsisch');
INSERT INTO "languages" VALUES(29,'cre','cr','cre','Cree','ᓀᐦᐃᔭᐤ(Nehiyāw)','Cree','cree','cree','克里语',NULL,NULL);
INSERT INTO "languages" VALUES(30,'cym','cy','wel','Indo-European','Cymraeg','Welsh','gallois','galés','威尔士语; 威尔斯语','валлийский','Walisisch');
INSERT INTO "languages" VALUES(31,'dan','da','dan','Indo-European','dansk','Danish','danois','danés','丹麦语','датский','Dänisch');
INSERT INTO "languages" VALUES(32,'deu','de','ger','Indo-European','Deutsch','German','allemand','alemán','德语','немецкий','Deutsch');
INSERT INTO "languages" VALUES(33,'div','dv','div','Indo-European','ދިވެހިބަސ','Divehi','maldivien','maldivo','迪维希语','дивехи','Dhivehi');
INSERT INTO "languages" VALUES(34,'dzo','dz','dzo','Sino-Tibetan','རྫོང་ཁ','Dzongkha','dzongkha','dzongkha','宗喀语; 不丹语','дзонг-кэ','Dzongkha');
INSERT INTO "languages" VALUES(35,'ell','el','gre','Indo-European','Ελληνικά','(New) Greek','grec (moderne)','griego (moderno)','现代希腊语','(ново)греческий','(Neu)griechisch');
INSERT INTO "languages" VALUES(36,'eng','en','eng','Indo-European','English','English','anglais','inglés','英语','английский','Englisch');
INSERT INTO "languages" VALUES(37,'epo','eo','epo','constructed','Esperanto','Esperanto','espéranto','esperanto','世界语','эсперанто','Esperanto');
INSERT INTO "languages" VALUES(38,'est','et','est','Uralic','eesti','Estonian','estonien','estonio','爱沙尼亚语','эстонский','Estnisch');
INSERT INTO "languages" VALUES(39,'eus','eu','baq','isolate','euskara','Basque','basque','euskera; vasco','巴斯克语','баскский','Baskisch');
INSERT INTO "languages" VALUES(40,'ewe','ee','ewe','Niger–Congo','Eʋegbe','Ewe','éwé','efé','埃维语; 幽语','эве','Ewe');
INSERT INTO "languages" VALUES(41,'fao','fo','fao','Indo-European','føroyskt','Faroese','féroïen','feroés','法罗斯语; 法罗语','фарерский','Färöisch');
INSERT INTO "languages" VALUES(42,'fas','fa','per','Indo-European','فارسی','Persian','persan','persa','波斯语','персидский','Persisch');
INSERT INTO "languages" VALUES(43,'fij','fj','fij','Austronesian','na vosa Vakaviti','Fijian','fidjien','fi(d)jiano','斐济语','фиджи','Fidschianisch');
INSERT INTO "languages" VALUES(44,'fin','fi','fin','Uralic','suomi','Finnish','finnois','fin(land)és','芬兰语','финский','Finnisch');
INSERT INTO "languages" VALUES(45,'fra','fr','fre','Indo-European','français','French','français','francés','法语','французский','Französisch');
INSERT INTO "languages" VALUES(46,'fry','fy','fry','Indo-European','Frysk','Frisian, Western','frison (occidental)',NULL,'弗里西亚语; 西弗里西亚语','западнофризский','Westfriesisch');
INSERT INTO "languages" VALUES(47,'ful','ff','ful','Niger–Congo','Fulfulde','Fulah','peul',NULL,'富拉语; 弗拉尼语','фулах','Ful');
INSERT INTO "languages" VALUES(48,'gla','gd','gla','Indo-European','Gàidhlig','Gaelic (Scots)','gaélique écossais','gaélico escocés',NULL,'шотландский гэльский','Schottisch-Gälisch');
INSERT INTO "languages" VALUES(49,'gle','ga','gle','Indo-European','Gaeilge','Irish','(gaélique) irlandais','irlandés','爱尔兰语','ирландский','Irisch');
INSERT INTO "languages" VALUES(50,'glg','gl','glg','Indo-European','galego','Galician','galicien','gallego','加利西亚语; 加里西亚语','галисийский','Galicisch');
INSERT INTO "languages" VALUES(51,'glv','gv','glv','Indo-European','Gaelg','Manx','manx','manés','马恩岛语; 曼岛语','мэнский','Manx');
INSERT INTO "languages" VALUES(52,'grn','gn','grn','Tupian','Avañe''ẽ','Guarani','guarani','guaraní','瓜拉尼语','гуарани','Guaraní');
INSERT INTO "languages" VALUES(53,'guj','gu','guj','Indo-European','ગુજરાતી','Gujarati','gujarâtî','guyaratí','古吉拉特语','гуджарати','Gujarati');
INSERT INTO "languages" VALUES(54,'hat','ht','hat','French Creole','kreyòl ayisyen','Haitian; Haitian Creole','haïtien; créole haïtien','criollo haitiano','海地克里奥尔语','гаити','Haitianisch');
INSERT INTO "languages" VALUES(55,'hau','ha','hau','Afro-Asiatic','حَوْسَ','Hausa','haoussa','hausa','豪萨语; 豪撒语','хауса','Hausa');
INSERT INTO "languages" VALUES(56,'hbs','sh',NULL,'Indo-European','српскохрватски / hrvatskosrpski','Serbo-Croatian','serbo-croate','serbocroata','塞尔维亚-克罗地亚语','сербохорватский','Serbokroatisch');
INSERT INTO "languages" VALUES(57,'heb','he','heb','Afro-Asiatic','עִבְרִית','Hebrew','hébreu','hebreo','希伯来语','иврит','Hebräisch; Iwrit');
INSERT INTO "languages" VALUES(58,'her','hz','her','Niger–Congo','Otjiherero','Herero','herero','herero','赫雷罗语','гереро','Otjiherero');
INSERT INTO "languages" VALUES(59,'hin','hi','hin','Indo-European','हिन्दी','Hindi','Hindi','Hindi','印地语','хинди','Hindi');
INSERT INTO "languages" VALUES(60,'hmo','ho','hmo','Austronesian',NULL,'Hiri Motu','hiri motu',NULL,'希里莫图语; 希里木托语','хиримоту','Hiri Motu');
INSERT INTO "languages" VALUES(61,'hrv','hr','hrv','Indo-European','hrvatski','Croatian','croate','croata','克罗地亚语; 克罗埃西亚语','хорватский','Kroatisch');
INSERT INTO "languages" VALUES(62,'hun','hu','hun','Uralic','magyar','Hungarian','hongrois','húngaro','匈牙利语','венгерский','Ungarisch');
INSERT INTO "languages" VALUES(63,'hye','hy','arm','Indo-European','Հայերեն','Armenian','arménien','armenio','亚美尼亚语','армянский','Armenisch');
INSERT INTO "languages" VALUES(64,'ibo','ig','ibo','Niger–Congo','Igbo','Igbo','igbo','igbo','伊博语','игбо','Igbo');
INSERT INTO "languages" VALUES(65,'ido','io','ido','constructed','Ido','Ido','ido','ido','伊多语','идо','Ido');
INSERT INTO "languages" VALUES(66,'iii','ii','iii','Sino-Tibetan','ꆇꉙ','Yi, Sichuan','yi de Sichuan',NULL,'四川彝语',NULL,NULL);
INSERT INTO "languages" VALUES(67,'iku','iu','iku','Eskimo–Aleut','ᐃᓄᒃᑎᑐᑦ','Inuktitut','inuktitut','inuktitut','伊努伊特语; 伊努特语; 因纽特语','инуктитут','Inuktitut');
INSERT INTO "languages" VALUES(68,'ile','ie','ile','constructed','Interlingue','Interlingue','interlingue','interlingue','西方国际语; 国际语E','интерлингве','Interlingue');
INSERT INTO "languages" VALUES(69,'ina','ia','ina','constructed','interlingua','Interlingua','interlingua','interlingua','国际语; 国际语A','интерлингва','Interlingua');
INSERT INTO "languages" VALUES(70,'ind','id','ind','Austronesian','bahasa Indonesia','Indonesian','indonésien','indonesio','印尼语','индонезийский','Indonesisch');
INSERT INTO "languages" VALUES(71,'ipk','ik','ipk','Eskimo–Aleut','Iñupiaq','Inupiaq','inupiaq','inupiaq','依努庇克语','инупиак','Inupiaq');
INSERT INTO "languages" VALUES(72,'isl','is','ice','Indo-European','íslenska','Icelandic','islandais','islandés','冰岛语','исландский','Isländisch');
INSERT INTO "languages" VALUES(73,'ita','it','ita','Indo-European','italiano','Italian','italien','italiano','意大利语; 义大利语','итальянский','Italienisch');
INSERT INTO "languages" VALUES(74,'jav','jv','jav','Austronesian','basa Jawa','Javanese','javanais','javanés','爪哇语','яванский','Javanisch');
INSERT INTO "languages" VALUES(75,'jpn','ja','jpn','Japonic','日本語','Japanese','japonais','japonés','日语','японский','Japanisch');
INSERT INTO "languages" VALUES(76,'kal','kl','kal','Eskimo–Aleut','kalaallisut','Kalaallisut','groenlandais','groenlandés','格陵兰语','гренландский','Kalaallisut');
INSERT INTO "languages" VALUES(77,'kan','kn','kan','Dravidian','ಕನ್ನಡ','Kannada','kannada','canarés','卡纳达语; 康纳达语','каннада','Kannada');
INSERT INTO "languages" VALUES(78,'kas','ks','kas','Indo-European','كشميري','Kashmiri','kashmiri','cachemir','克什米尔语','кашмири','Kashmiri');
INSERT INTO "languages" VALUES(79,'kat','ka','geo','Kartvelian','ქართული','Georgian','géorgien','georgiano','格鲁吉亚语; 乔治亚语','грузинский','Georgisch');
INSERT INTO "languages" VALUES(80,'kau','kr','kau','Nilo-Saharan','kanuri','Kanuri','kanouri','canurí','卡努里语','канури','Kanuri');
INSERT INTO "languages" VALUES(81,'kaz','kk','kaz','Turkic','Қазақша','Kazakh','kazakh','kazaj(i)o','哈萨克语','казахский','Kasachisch');
INSERT INTO "languages" VALUES(82,'khm','km','khm','Austroasiatic','ខ្មែរ','Khmer','khmer','jemer','高棉语','кхмерский',NULL);
INSERT INTO "languages" VALUES(83,'kik','ki','kik','Niger–Congo','Gĩkũyũ','Kikuyu','kikuyu','quicuyú','基库尤语; 吉库尤语','кикуйю','Kikuyu');
INSERT INTO "languages" VALUES(84,'kin','rw','kin','Niger–Congo','kinyaRwanda','Kinyarwanda','rwanda','ruandés','基尼阿万达语; 卢安达语','киньяруанда','Kinyarwanda');
INSERT INTO "languages" VALUES(85,'kir','ky','kir','Turkic','Кыргыз','Kyrgyz','kirghize','kirguís','吉尔吉斯语; 柯尔克孜语','киргизский','Kirgisisch');
INSERT INTO "languages" VALUES(86,'kom','kv','kom','Uralic','коми','Komi','kom','komi','科米语','коми','Komi');
INSERT INTO "languages" VALUES(87,'kon','kg','kon','Niger–Congo','Kikongo','Kongo','kongo','kongo','刚果语','конго','Kikongo');
INSERT INTO "languages" VALUES(88,'kor','ko','kor','Koreanic','한국어','Korean','coréen','coreano','朝鲜语; 韩语','корейский','Koreanisch');
INSERT INTO "languages" VALUES(89,'kua','kj','kua','Niger–Congo','kuanyama','Kuanyama','kuanyama',NULL,'宽亚玛语; 贡耶玛语','кваньяма',NULL);
INSERT INTO "languages" VALUES(90,'kur','ku','kur','Indo-European','Kurdî','Kurdish','kurde','kurdo','库尔德语; 库德语','курдский','Kurdisch');
INSERT INTO "languages" VALUES(91,'lao','lo','lao','Tai–Kadai','ພາສາລາວ','Lao','lao','laosiano','老挝语; 寮国语','лаосский','Laotisch');
INSERT INTO "languages" VALUES(92,'lat','la','lat','Indo-European','lingua Latīna','Latin','latin','latín','拉丁语','латинский','Latein(isch)');
INSERT INTO "languages" VALUES(93,'lav','lv','lav','Indo-European','latviešu','Latvian','letton','letón','拉脱维亚语','латышский','Lettisch');
INSERT INTO "languages" VALUES(94,'lim','li','lim','Indo-European','Lèmburgs','Limburgish, Limburgan','limbourgeois',NULL,'林堡语','лимбургский','Limburgisch');
INSERT INTO "languages" VALUES(95,'lin','ln','lin','Niger–Congo','Lingala','Lingala','lingala','lingala','林加拉语; 林格拉语','лингала','Lingala');
INSERT INTO "languages" VALUES(96,'lit','lt','lit','Indo-European','lietuvių','Lithuanian','lituanien','lituano','立陶宛语','литовский','Litauisch');
INSERT INTO "languages" VALUES(97,'ltz','lb','ltz','Indo-European','Lëtzebuergesch','Luxembourgish; Letzeburgesch','luxembourgeois','luxemburgués','卢森堡语','люксембургский','Luxemburgisch');
INSERT INTO "languages" VALUES(98,'lub','lu','lub','Niger–Congo',NULL,'Luba-Katanga','luba-katanga',NULL,'卢巴-加丹加语; 卢巴卡丹加语','луба-катанга',NULL);
INSERT INTO "languages" VALUES(99,'lug','lg','lug','Niger–Congo','Luganda','Luganda','ganda','luganda','干达语; 卢干达语','ганда','Luganda');
INSERT INTO "languages" VALUES(100,'mah','mh','mah','Austronesian','Kajin M̧ajeļ','Marshall','marshall',NULL,'马绍尔语','маршал(л)ьский','Marshallisch');
INSERT INTO "languages" VALUES(101,'mal','ml','mal','Dravidian','മലയാളം','Malayalam','malayalam','malayalam','马拉雅拉姆语','малаялам','Malajalam');
INSERT INTO "languages" VALUES(102,'mar','mr','mar','Indo-European','मराठी','Marathi','marathe','maratí','马拉地语','маратхи','Marathi');
INSERT INTO "languages" VALUES(103,'mkd','mk','mac','Indo-European','македонски','Macedonian','macédonien','macedonio','马其顿语','македонский','Mazedonisch');
INSERT INTO "languages" VALUES(104,'mlg','mg','mlg','Austronesian','Malagasy','Malagasy','malgache','mal(a)gache','马达加斯加语、马拉加西语','малагасийский','Madegassisch');
INSERT INTO "languages" VALUES(105,'mlt','mt','mlt','Afro-Asiatic','bil-Malta','Maltese','maltais','maltés','马耳他语; 马尔他语','мальтийский','Maltesisch');
INSERT INTO "languages" VALUES(106,'mon','mn','mon','Mongolic','монгол','Mongolian','mongol','mongol','蒙古语','монгольский','Mongolisch');
INSERT INTO "languages" VALUES(107,'mri','mi','mao','Austronesian','te reo Māori','Maori','maori','maorí','毛利语','маори','Maori');
INSERT INTO "languages" VALUES(108,'msa','ms','may','Austronesian','bahasa Melayu','Malay (generic)','malais','malayo','马来语','малайский','Malaiisch');
INSERT INTO "languages" VALUES(109,'mya','my','bur','Sino-Tibetan','မြန်မာစာ','Burmese','birman','birmano','缅甸语','бирманский','Burmesisch');
INSERT INTO "languages" VALUES(110,'nau','na','nau','Austronesian','ekakairũ naoero','Nauru','nauruan','nauruano','瑙鲁语; 诺鲁语','науру','Nauruisch');
INSERT INTO "languages" VALUES(111,'nav','nv','nav','Dené–Yeniseian','Diné bizaad','Navajo','navaho','navajo','纳瓦霍语; 纳瓦荷语','навахо','Navajo');
INSERT INTO "languages" VALUES(112,'nbl','nr','nbl','Niger–Congo','Ndébélé','Ndebele, South','ndébélé du Sud',NULL,'南恩德贝勒语','южный ндебеле',NULL);
INSERT INTO "languages" VALUES(113,'nde','nd','nde','Niger–Congo','isiNdebele','Ndebele, North','ndébélé du Nord',NULL,'北恩德贝勒语','северный ндебеле',NULL);
INSERT INTO "languages" VALUES(114,'ndo','ng','ndo','Niger–Congo','O(shi)wambo','Ndonga','ndonga',NULL,'恩敦加语; 恩东加语','ндонга',NULL);
INSERT INTO "languages" VALUES(115,'nep','ne','nep','Indo-European','नेपाली','Nepali','népalais','nepalí','尼泊尔语','непали','Nepali');
INSERT INTO "languages" VALUES(116,'nld','nl','dut','Indo-European','Nederlands','Dutch','néerlandais','neerlandés','荷兰语','нидерландский','Niederländisch');
INSERT INTO "languages" VALUES(117,'nno','nn','nno','Indo-European','Nynorsk','Norwegian Nynorsk','norvégien nynorsk','noruego nynorsk','新挪威语','нюнорск','Nynorsk');
INSERT INTO "languages" VALUES(118,'nob','nb','nob','Indo-European','Bokmål','Norwegian Bokmål','norvégien bokmål','noruego bokmål','挪威布克莫尔语; 书面挪威语; 波克莫尔语','букмол','Norwegische Bokmål');
INSERT INTO "languages" VALUES(119,'nor','no','nor','Indo-European','norsk','Norwegian','norvégien','noruego','挪威语','норвежский','Norwegisch');
INSERT INTO "languages" VALUES(120,'nya','ny','nya','Niger–Congo','chiCheŵa','Chichewa; Nyanja','nyanja','ñanya','尼昂加语; 齐切瓦语','ньянджа','Nyanja');
INSERT INTO "languages" VALUES(121,'oci','oc','oci','Indo-European','occitan','Occitan (post 1500)','occitan (après 1500)','occitano','奥克西唐语; 奥克西坦语; 奥克语','окситанский','Okzitanisch');
INSERT INTO "languages" VALUES(122,'oji','oj','oji','Cree','ᐊᓂᔑᓇᐯᒧᐎᓐ (Anishinaabemowin)','Ojibwa','ojibwa','ojibwa','奥吉布瓦语','оджибва',NULL);
INSERT INTO "languages" VALUES(123,'ori','or','ori','Indo-European','ଓଡ଼ିଆ','Oriya','oriya','oriya','奥利亚语; 奥里亚语','ория','Oriya');
INSERT INTO "languages" VALUES(124,'orm','om','orm','Afro-Asiatic','Oromoo','Oromo','galla','oromo','奥罗莫语','оромо','Oromo');
INSERT INTO "languages" VALUES(125,'oss','os','oss','Indo-European','иронау','Ossetian','ossète','oseto','奥塞梯语; 奥塞提语','осетинский','Ossetisch');
INSERT INTO "languages" VALUES(126,'pan','pa','pan','Indo-European','ਪੰਜਾਬੀ','Panjabi; Punjabi','pendjabi','panyabí','旁遮普语','пенджаби','Pandschabisch');
INSERT INTO "languages" VALUES(127,'pli','pi','pli','Indo-European','पालि, पाळि','Pali','pali',NULL,'巴利语','пали','Pali');
INSERT INTO "languages" VALUES(128,'pol','pl','pol','Indo-European','polski','Polish','polonais','polaco','波兰语','польский','Polnisch');
INSERT INTO "languages" VALUES(129,'por','pt','por','Indo-European','português','Portuguese','portugais','portugués','葡萄牙语','португальский','Portugiesisch');
INSERT INTO "languages" VALUES(130,'pus','ps','pus','Indo-European','پښتو','Pushto','pachto','pastú','普什图语; 帕图语','пушту','Paschtunisch');
INSERT INTO "languages" VALUES(131,'que','qu','que','Quechuan','Runa Simi','Quechua','quechua','quechua','克丘亚语; 凯楚亚语; 奇楚瓦语','кечуа','Quechua');
INSERT INTO "languages" VALUES(132,'roh','rm','roh','Indo-European','rumantsch','Raeto-Romance','rhéto-roman','retorrománico','罗曼什语','ретороманский','Rätoromanisch');
INSERT INTO "languages" VALUES(133,'ron','ro','rum','Indo-European','română','Romanian','roumain','rumano','罗马尼亚语','румынский','Rumänisch');
INSERT INTO "languages" VALUES(134,'run','rn','run','Niger–Congo','kiRundi','Rundi','rundi','rundí','基隆迪语; 克伦地语','рунди','Kirundi');
INSERT INTO "languages" VALUES(135,'rus','ru','rus','Indo-European','русский','Russian','russe','ruso','俄语','русский','Russisch');
INSERT INTO "languages" VALUES(136,'sag','sg','sag','Creole','sängö','Sango','sango','sango','桑戈语','санго','Sango');
INSERT INTO "languages" VALUES(137,'san','sa','san','Indo-European','संस्कृतम्','Sanskrit','sanskrit','sánscrito','梵语','санскрит','Sanskrit');
INSERT INTO "languages" VALUES(138,'sin','si','sin','Indo-European','සිංහල','Sinhala; Sinhalese','singhalais','cingalés','僧加罗语; 僧伽罗语','сингальский','Singhalesisch');
INSERT INTO "languages" VALUES(139,'slk','sk','slo','Indo-European','slovenčina','Slovak','slovaque','eslovaco','斯洛伐克语','словацкий','Slowakisch');
INSERT INTO "languages" VALUES(140,'slv','sl','slv','Indo-European','slovenščina','Slovenian','slovène','esloveno','斯洛文尼亚语、斯洛维尼亚语','словенский','Slowenisch');
INSERT INTO "languages" VALUES(141,'sme','se','sme','Uralic','sámi','Northern Sami','sami du Nord',NULL,'北萨米语','северносаамский','Nordsamisch');
INSERT INTO "languages" VALUES(142,'smo','sm','smo','Austronesian','gagana Samoa','Samoan','samoan','samoano','萨摩亚语','самоанский','Samoanisch');
INSERT INTO "languages" VALUES(143,'sna','sn','sna','Niger–Congo','chiShona','Shona','shona','sonés','修纳语; 绍纳语','шона','Shona');
INSERT INTO "languages" VALUES(144,'snd','sd','snd','Indo-European','سندھی','Sindhi','sindhî','sindí','信德语; 辛德语','синдхи','Sindhi');
INSERT INTO "languages" VALUES(145,'som','so','som','Afro-Asiatic','Soomaaliga','Somali','somali','somalí','索马里语; 索马利亚语','сомали','Somalisch');
INSERT INTO "languages" VALUES(146,'sot','st','sot','Niger–Congo','Sesotho','Sotho, Southern','sotho du Sud','sesotho','南索托语','сесото','Sesotho');
INSERT INTO "languages" VALUES(147,'spa','es','spa','Indo-European','español','Spanish (Castilian)','espagnol','español','西班牙语','испанский','Spanisch');
INSERT INTO "languages" VALUES(148,'sqi','sq','alb','Indo-European','Shqip','Albanian','albanais','albanés','阿尔巴尼亚语','албанский','Albanisch');
INSERT INTO "languages" VALUES(149,'srd','sc','srd','Indo-European','sardu','Sardinian','sarde','sardo','撒丁语, 萨丁尼亚语','сардинский','Sardisch');
INSERT INTO "languages" VALUES(150,'srp','sr','srp','Indo-European','српски / srpski','Serbian','serbe','serbio','塞尔维亚语','сербский','Serbisch');
INSERT INTO "languages" VALUES(151,'ssw','ss','ssw','Niger–Congo','siSwati','Swati','swati','swati','斯瓦特语; 史瓦济兰语','свати','Siswati');
INSERT INTO "languages" VALUES(152,'sun','su','sun','Austronesian','basa Sunda','Sundanese','soundanais','sundanés','巽他语','сунданский','Sundanesisch');
INSERT INTO "languages" VALUES(153,'swa','sw','swa','Niger–Congo','kiswahili','Swahili (generic)','swahili','suahelí','斯瓦希里语; 斯瓦西里语','суахили','Suaheli');
INSERT INTO "languages" VALUES(154,'swe','sv','swe','Indo-European','svenska','Swedish','suédois','sueco','瑞典语','шведский','Schwedisch');
INSERT INTO "languages" VALUES(155,'tah','ty','tah','Austronesian','te reo Tahiti','Tahitian','tahitien','tahitiano','塔希提语、大溪地语','таитянский','Tahitianisch');
INSERT INTO "languages" VALUES(156,'tam','ta','tam','Dravidian','தமிழ்','Tamil','tamoul','Tamil','泰米尔语; 坦米尔语; 淡米尔语','тамильский','Tamilisch');
INSERT INTO "languages" VALUES(157,'tat','tt','tat','Turkic','Tatarça','Tatar','tatar','tártaro','塔塔尔语; 鞑靼语','татарский','Tatarisch');
INSERT INTO "languages" VALUES(158,'tel','te','tel','Dravidian','తెలుగు','Telugu','télougou','telugú','泰卢固语','телугу','Telugu');
INSERT INTO "languages" VALUES(159,'tgk','tg','tgk','Indo-European','тоҷикӣ','Tajik','tadjik','tayiko','塔吉克语','таджикский','Tadschikisch');
INSERT INTO "languages" VALUES(160,'tgl','tl','tgl','Austronesian','Tagálog','Tagalog','Tagalog','tagalo(g)','塔加洛语; 塔加拉语; 他加禄语','тагальский','Tagalog');
INSERT INTO "languages" VALUES(161,'tha','th','tha','Tai–Kadai','ภาษาไทย','Thai','thaï(landais)','tailandés','泰语','тайский','Thai(ländisch)');
INSERT INTO "languages" VALUES(162,'tir','ti','tir','Afro-Asiatic','ትግርኛ','Tigrinya','tigrigna','tigriña','提格里尼亚语、提格利尼亚语','тигринья','Tigrinja');
INSERT INTO "languages" VALUES(163,'ton','to','ton','Austronesian','faka-Tonga','Tonga (Tonga Islands)','Tongan (Îles Tonga)','tongano','汤加语; 东加语','тонга (Тонга исландский)','Tongaisch');
INSERT INTO "languages" VALUES(164,'tsn','tn','tsn','Niger–Congo','Setswana','Tswana','tswana','setsuana','茨瓦纳语','тсвана','Tsuana');
INSERT INTO "languages" VALUES(165,'tso','ts','tso','Niger–Congo','Xitsonga','Tsonga','tsonga','tsonga','聪加语; 宗加语','тсонга','Tsongaisch');
INSERT INTO "languages" VALUES(166,'tuk','tk','tuk','Turkic','Түркмен','Turkmen','turkmène','turcomano','土库曼语','туркменский','Turkmenisch');
INSERT INTO "languages" VALUES(167,'tur','tr','tur','Turkic','Türkçe','Turkish','Turc','Turco','土耳其语','турецкий','Türkisch');
INSERT INTO "languages" VALUES(168,'twi','tw','twi','Niger–Congo','Twi','Twi','twi','twi','契维语; 特威语; 多威语','тви','Twi');
INSERT INTO "languages" VALUES(169,'uig','ug','uig','Turkic','ئۇيغۇرچە','Uighur','ouïgour','uigur','维吾尔语','уйгурский','Uigurisch');
INSERT INTO "languages" VALUES(170,'ukr','uk','ukr','Indo-European','українська','Ukrainian','ukrainien','ucrani(an)o','乌克兰语','украинский','Ukrainisch');
INSERT INTO "languages" VALUES(171,'urd','ur','urd','Indo-European','اردو','Urdu','ourdou','Urdu','乌尔都语; 乌都语; 晤鲁都语','урду','Urdu');
INSERT INTO "languages" VALUES(172,'uzb','uz','uzb','Turkic','Ўзбек','Uzbek','ou(s)zbek','uzbeco','乌兹别克语; 乌孜别克语','узбекский','Usbekisch');
INSERT INTO "languages" VALUES(173,'ven','ve','ven','Niger–Congo','Tshivenḓa','Venda','venda','venda','文达语; 温达语','венда','Tshivenda');
INSERT INTO "languages" VALUES(174,'vie','vi','vie','Austroasiatic','tiếng Việt','Vietnamese','vietnamien','vietnamita','越南语; 京语','вьетнамский','Vietnamesisch');
INSERT INTO "languages" VALUES(175,'vol','vo','vol','constructed','volapük','Volapük','volapük','volapük','沃拉普克语','волапюк','Volapük');
INSERT INTO "languages" VALUES(176,'wln','wa','wln','Indo-European','walon','Walloon','wallon',NULL,'瓦龙语; 瓦隆语; 华隆语','валлонский','Wallonisch');
INSERT INTO "languages" VALUES(177,'wol','wo','wol','Niger–Congo','Wolof','Wolof','wolof','volofo','沃洛夫语; 渥鲁夫语','волоф','Wolof');
INSERT INTO "languages" VALUES(178,'xho','xh','xho','Niger–Congo','isiXhosa','Xhosa','xhosa','xhosa','科萨语','коса','Xhosa');
INSERT INTO "languages" VALUES(179,'yid','yi','yid','Indo-European','אידיש','Yiddish','Yiddish',NULL,'依地语; 意第绪语','идиш','Jiddisch');
INSERT INTO "languages" VALUES(180,'yor','yo','yor','Niger–Congo',NULL,'Yoruba','yoruba',NULL,'约鲁巴语',NULL,NULL);
INSERT INTO "languages" VALUES(181,'zha','za','zha','Tai–Kadai',NULL,'Zhuang','zhuang',NULL,'壮语','чжуанский',NULL);
INSERT INTO "languages" VALUES(182,'zho','zh','chi','Chinese','中文; 汉语; 华语','Chinese','chinois',NULL,'中文; 汉语; 华语','китайский','Chinesisch');
INSERT INTO "languages" VALUES(183,'zul','zu','zul','Niger–Congo','isiZulu','Zulu','zoulou',NULL,'祖鲁语','зулу',NULL);
